---
- hosts: web
#  serial: 1
  name: This is a play within a playbook
  become: true
  vars:
    httpd_packages:
      - httpd
      - httpd-devel
      - mod_wsgi
    apache_test_message: This is a test message for the Ansible 101 workshop
    apache_max_keep_alive_requests: 115
    apache_webserver_port: 80

  tasks:
    - name: install httpd packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ httpd_packages }}"
      notify: restart web

    - name: create site-enabled directory
      file:
        name: /etc/httpd/conf/sites-enabled
        state: directory

    - name: copy httpd.conf
      template:
        src: templates/04-httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
      notify: restart web

    - name: copy index.html
      template:
        src: templates/04-index.html.j2
        dest: /var/www/html/index.html

    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes

  handlers:
    - name: restart apache service
      service:
        name: httpd
        state: restarted
        enabled: yes
      listen: restart web
